apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-log
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath: 
    path: /mnt/data
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
