apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
    - name: alpine
      image: alpine
      command: ['sleep', '3600']
      env:
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config 
              key: APP_COLOR
        - name: APP_MODE
          valueFrom:
            configMapKeyRef: 
              name: app-config
              key: APP_MODE
