apiVersion: v1
kind: Pod 
metadata:
  name: pod-delete
spec: 
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-data
          mountPath: /var/www/html
  volumes:
    - name: nginx-data
      persistentVolumeClaim: 
        claimName: pvc-dynamic
