apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-rs
  template: 
    metadata:
      labels:
        app: flask-rs
    spec:
      containers:
      - name: flask
        image: thanhtutln2020/flask-app:latest
        ports:
        - containerPort: 5000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: "In"
                values:
                - cluster-worker2
