cluster:
  name: cluster2
  id: 2

operator:
  clusterPoolIPv4PodCIDRList: ["10.2.0.0/16"]
  clusterPoolIPv4MaskSize: 24

ipam:
  mode: kubernetes

kubeProxyReplacement: true

clustermesh:
  enable: true
  serviceType: LoadBalancer
  apiserver:
    replicas: 1
    service:
      type: LoadBalancer
  config:
    clusters:
    - name: cluster1
      address: 10.4.1.100:2379
