apiVersion: v1
kind: Pod
metadata:
  name: side-cars
spec: 
  restartPolicy: OnFailure
  containers:
    - name: main-app
      image: nginx:1.14.2
      ports:
        - containerPort: 80
  initContainers:
    - name: logging
      image: fluent/fluent-bit:1.8
      restartPolicy: Always