apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: flask
    image: thanhtutln2020/flask-app:latest
    ports:
    - containerPort: 5000
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector: 
            matchExpressions:
            - key: "app"
              operator: "In"
              values:
                - "flask-rs"
          topologyKey: "beta.kubernetes.io/arch"
