# delete policy will be delete backend path from node (dynamicProvision)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-provision
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - name: data
          mountPath: /var/www/html
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: dynamic-provision