apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: shell
    image: debian
    command: ['sleep', 'infinity']
    volumeMounts: 
      - name: artifacts
        mountPath: /data
  volumes: 
    - name: artifacts
      image: 
        reference: quay.io/crio/artifact:v2
        pullPolicy: IfNotPresent