apiVersion: v1
kind: Pod
metadata:
  name: project-volume-example
spec: 
  containers:
    - name: busybox
      image: busybox:1.28
      command: ["sleep", "3600"]
      volumeMounts:
        - name: all-in-one
          mountPath: "/projected-volume"
          readOnly: true
  volumes:
    - name: all-in-one
      projected: 
        sources:
          - secret:
              name: my-secret
              items:
                - key: username
                  path: my-group/my-username
                - key: password
                  path: my-group/my-password
          - configMap:
              name: myconfigmap
              items:
                - key: config
                  path: my-group/my-config 
          - downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels
