# delete policy will be delete backend path from node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: retain-for-pv
spec:
  capacity:
    storage: 500Mi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  hostPath: 
    path: /data/static-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reatin-for-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: ''
---
apiVersion: v1
kind: Pod
metadata:
  name: retain-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: data
        mountPath: /var/www/html
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: reatin-for-pvc