apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: Immediate
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata: 
#  name: immediate-pvc 
#spec: 
#  accessModes: 
#    - ReadWriteOnce
#  volumeMode: Filesystem 
#  resources:
#    requests:
#      storage: 10Gi
#  storageClassName: standard 