---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-lab-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 172.18.0.1
    path: /srv/nfs/nfs-lab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-lab-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: nfs-lab-pv
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: nfs-test-pod
#spec:
#  containers:
#  - name: web-server
#    image: nginx
#    volumeMounts:
#    - name: nfs-storage
#      mountPath: /usr/share/nginx/html
#  volumes:
#  - name: nfs-storage
#    persistentVolumeClaim:
#      claimName: nfs-lab-pvc