apiVersion: v1
kind: Pod
metadata:
  name: volume-mount
spec:
  volumes: 
    - name: volume-secret-mounts
      secret:
        secretName: yaml-secret
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "ls /etc/secret-vol; cat /etc/secret-vol/username; cat /etc/secret-vol/password; sleep 3600"]
      volumeMounts:
        - name: volume-secret-mounts 
          mountPath: /etc/secret-vol
          readOnly: true 
