apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: prod
spec: 
  containers: 
    - image: nginx:alpine
      name: nginx
      volumeMounts:
        - name: web-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: web-volume
      persistentVolumeClaim:
        claimName: pvc-data 
