apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: service-lab
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: nginx
    name: nginx
    protocol: TCP
  externalTrafficPolicy: Local