apiVersion: v1
kind: Pod
metadata:
  name: ctr-size
spec: 
  containers: 
    - name: ctr
      image: alpine
      command: ['sh', '-c', 'sleep infinity']
      resources:
        requests:
          memory: '500Mi'
          cpu: '500m'
        limits: 
          cpu: '1000m'
          memory: '1Gi'
    - name: ctr2
      image: alpine
      command: ['sh', '-c', 'sleep infinity']
      resources:
        requests:
          memory: '500Mi'
          cpu: '500m'
        limits: 
          cpu: '1000m'
          memory: '1Gi'
