apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flask-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: thanhtutln2020/flask-app:latest
        name: flask
        ports:
        - containerPort: 5000
