---
apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod-ns
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  tolerations:
  - key: "environment"
    value: "production"
    operator: "Equal"
    effect: "NoSchedule"

---
apiVersion: v1
kind: Pod
metadata:
  name: without-toleration-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: no-execute
spec:
  replicas: 3 
  selector: 
    matchLabels:
      app: tolerant
  template: 
    metadata: 
      labels:
        app: tolerant 
    spec: 
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
      tolerations: 
        - key: "environment"
          value: "true"
          operator: "Equal"
          effect: "NoExecute"

