# complete-lab.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-noschedule
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: test-preferschedule
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: test-noexecute
spec:
  containers:
  - name: nginx
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: test-all-tolerations
spec:
  containers:
  - name: nginx
    image: nginx:latest
  tolerations:
  - key: "environment"
    operator: "Equal"
    value: "production"
    effect: "NoSchedule"
  - key: "environment"
    operator: "Equal"
    value: "staging"
    effect: "PreferNoSchedule"
  - key: "environment"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
