apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox:1.36
            command: ['sh', '-c', date; echo 'Hello']
          restartPolicy: OnFailure 
