apiVersion: apps/v1 
kind: DaemonSet
metadata:
  name: daemonset
spec:
  selector:
    matchLabels:
      app: daemon-set
  template:
    metadata:
      labels:
        app: daemon-set
    spec:
      containers:
      - name: flask
        image: thanhtutln2020/flask-app:latest
        ports:
        - containerPort: 5000
      tolerations:
      - key: "node-role.kubernetes.io/control-plane" 
        effect: "NoSchedule"
        operator: "Equal" 
